### ISSUE TITLE
I couldn't run electron demo

### ISSUE THREAD

**Issue by jsveron23** [sencha/electron-demo#9]
Hi,

After type this `npm run app',

```
[INF] Processing Build Descriptor : default
[WRN] Failed to resolve package ext-electron
[ERR] The following error occurred while executing this line:
[dir]/electron-demo/app/build.xml:8: Cannot find [dir]/electron-demo/app/.sencha/app/build-impl.xml imported from [dir]/electron-demo/app/build.xml
```

I couldn't find `app/.sencha/app` directory also...

Do you have any idea?

**Comment by tvaughan73** [comment]
I am having the same issue.

**Comment by tvaughan73** [comment]
I was able to get setup to complete only after I installed CMD 6.5.  CMD 6.2 would not work.
  CMD 6.5 is part of the EA releases.

**Comment by jsveron23** [comment]
It works. Thank you!
